Skip to content
 
Search or jump to…

Pull requests
Issues
Marketplace
Explore
 @shivaprasad57 Sign out
0
0 91 shivaprasad57/aws-nodejs-sample-codebuild
forked from backspace-academy/aws-nodejs-sample-codebuild
 Code  Pull requests 0  Projects 0  Wiki  Insights  Settings
aws-nodejs-sample-codebuild/buildspec.yml
25a1680  on Sep 12, 2017
@backspace-academy backspace-academy .
     
33 lines (31 sloc)  1000 Bytes
# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  install:
    commands:
      - echo Installing Mocha...
      - npm install -g mocha
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install unit.js
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - mocha test.js
  post_build:
    commands:
      - echo Build completed on `date`
# Include only the files required for your application to run.
# Do not use recursively include artifacts from node_modules directory as it will include unnecessary packages 
# used only for building and testing.
# ExpressJS apps will need other artifact directories included (bin/*, public/*, routes/*, views/* etc).
artifacts:
  files:
    - app.js
    - index.html
    - package.json
    - node_modules/async/*
    - node_modules/lodash/*
© 2018 GitHub, Inc.
Terms
Privacy
Security
Status
Help
Contact GitHub
Pricing
API
Training
Blog
About
Press h to open a hovercard with more details.
